version: '3'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/first_service
      - SPRING_DATASOURCE_USERNAME=andrew
      - SPRING_DATASOURCE_PASSWORD=andrew
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=andrew
      - POSTGRES_USER=andrew
      - POSTGRES_DB=first_service
    restart: always